// SPDX-FileCopyrightText: 2026 PixeLabs
// SPDX-License-Identifier: AGPL-3.0-or-later
// Additional terms under AGPL section 7 apply: see COPYING.additional-terms.

//! Phase E asset gates (spec tasks E6/E3, §4.3):
//!
//! * The committed `assets/color/looks/*.lblook` files are the canonical
//!   serialization of the code-authored looks ([`author_lightbox_color_v1`] /
//!   [`author_lightbox_neutral`]), reproducible under `LIGHTBOX_BLESS=1`,
//!   asserted equal otherwise.
//! * The committed `scene-corpus.toml` mirrors [`scene_corpus`] exactly.
//! * The surface-3 `assets/MANIFEST.toml` **policy checker**: every file under
//!   `assets/color/` has a cleared manifest entry, provenance is in the allowed
//!   set, and **nothing is Adobe-authored** (constraint 4).
//!
//! Bless flow mirrors the golden harness: `LIGHTBOX_BLESS=1 cargo test`
//! regenerates the committed assets locally (and refuses in CI).

use std::path::{Path, PathBuf};

use lbx_image_compare::bless_requested;
use lightbox_color::look::{
    author_lightbox_color_v1, author_lightbox_neutral, load_look, scene_corpus, Look,
};

/// Repo root (two levels up from this crate's manifest dir).
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("repo root resolves")
}

fn assets_dir() -> PathBuf {
    repo_root().join("assets")
}

fn running_in_ci() -> bool {
    match std::env::var("CI") {
        Ok(v) => !v.is_empty() && !v.eq_ignore_ascii_case("false"),
        Err(_) => false,
    }
}

/// Asserts the two looks decode-equal on every field that survives a round-trip.
fn assert_look_eq(loaded: &Look, authored: &Look) {
    assert_eq!(loaded.name, authored.name, "look name");
    assert_eq!(loaded.version, authored.version, "look version");
    assert_eq!(
        loaded.tone_curve.control_points, authored.tone_curve.control_points,
        "tone curve"
    );
    assert_eq!(loaded.provenance, authored.provenance, "provenance");
    match (&loaded.hue_sat, &authored.hue_sat) {
        (Some(a), Some(b)) => {
            assert_eq!(a.dims, b.dims);
            assert_eq!(a.deltas, b.deltas);
            assert_eq!(a.encoding, b.encoding);
        }
        (None, None) => {}
        _ => panic!("hue_sat presence differs for {}", authored.name),
    }
}

/// E6: the committed `.lblook` assets are the canonical serialization of the
/// code-authored looks. Bless regenerates them; otherwise they must match.
#[test]
fn committed_lblook_assets_match_the_authored_looks() {
    let looks_dir = assets_dir().join("color").join("looks");
    let cases = [
        ("lightbox-color-v1.lblook", author_lightbox_color_v1()),
        ("lightbox-neutral.lblook", author_lightbox_neutral()),
    ];

    if bless_requested() {
        assert!(!running_in_ci(), "LIGHTBOX_BLESS must never be set in CI");
        std::fs::create_dir_all(&looks_dir).unwrap();
        for (file, look) in &cases {
            std::fs::write(looks_dir.join(file), look.to_bytes().unwrap()).unwrap();
        }
        return;
    }

    for (file, authored) in &cases {
        let path = looks_dir.join(file);
        let bytes = std::fs::read(&path).unwrap_or_else(|e| {
            panic!(
                "missing committed asset {} ({e}): run `LIGHTBOX_BLESS=1 cargo test -p \
                 lightbox-color` and commit",
                path.display()
            )
        });
        let loaded = load_look(&bytes).expect("committed .lblook loads");
        assert_look_eq(&loaded, authored);
        // Provenance affidavit is carried in the shipped bytes (E5).
        assert_eq!(loaded.provenance.author, "lightbox-authored");
        assert_eq!(loaded.provenance.license, "project");
        assert!(
            !loaded.provenance.author.to_lowercase().contains("adobe"),
            "no Adobe-authored content"
        );
    }
}

// --- Scene-corpus manifest (E3) ---

#[derive(serde::Serialize, serde::Deserialize)]
struct SceneManifest {
    scene: Vec<SceneEntry>,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct SceneEntry {
    name: String,
    category: String,
    license: String,
}

/// E3: the committed scene-corpus manifest lists exactly the synthetic scenes
/// [`scene_corpus`] produces (names + categories), each with a license.
#[test]
fn committed_scene_corpus_manifest_matches_the_corpus() {
    let path = assets_dir()
        .join("color")
        .join("looks")
        .join("scene-corpus.toml");
    let corpus = scene_corpus();
    let expected: Vec<SceneEntry> = corpus
        .iter()
        .map(|s| SceneEntry {
            name: s.name.clone(),
            category: s.category.clone(),
            license: "project (synthetic, generated by lightbox)".to_owned(),
        })
        .collect();

    if bless_requested() {
        assert!(!running_in_ci(), "LIGHTBOX_BLESS must never be set in CI");
        let doc = SceneManifest { scene: expected };
        let header =
            "# Synthetic scene corpus for the Lightbox look-dev harness (spec E02 task E3).\n\
            # Project-generated (NOT photographic) — real CC0 photographic scenes are deferred\n\
            # until the raw corpus + LibRaw proxy land (see docs/plan/epics/E02-deviations.md).\n\
            # Generated from lightbox_color::look::scene_corpus() via `LIGHTBOX_BLESS=1`; kept in\n\
            # sync by the look_assets integration test.\n\n";
        let body = toml::to_string_pretty(&doc).unwrap();
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, format!("{header}{body}")).unwrap();
        return;
    }

    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing {} ({e}): run `LIGHTBOX_BLESS=1 cargo test -p lightbox-color` and commit",
            path.display()
        )
    });
    let doc: SceneManifest = toml::from_str(&text).expect("scene-corpus.toml parses");
    assert_eq!(
        doc.scene.len(),
        corpus.len(),
        "scene count drifted from the corpus"
    );
    for (entry, scene) in doc.scene.iter().zip(corpus.iter()) {
        assert_eq!(entry.name, scene.name, "scene name/order drift");
        assert_eq!(entry.category, scene.category, "scene category drift");
        assert!(!entry.license.is_empty(), "scene missing a license");
    }
}

// --- Surface-3 manifest policy checker (E6 / §4.3) ---

#[derive(serde::Deserialize)]
struct Manifest {
    #[serde(default)]
    asset: Vec<AssetEntry>,
}

#[derive(serde::Deserialize)]
struct AssetEntry {
    path: String,
    kind: String,
    provenance: String,
    license: String,
    #[serde(default)]
    copyright: Option<String>,
}

/// Recursively lists files under `dir`, returned as paths relative to `base`
/// with `/` separators.
fn list_files_rel(base: &Path, dir: &Path, out: &mut Vec<String>) {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in rd.flatten() {
        let p = entry.path();
        if p.is_dir() {
            list_files_rel(base, &p, out);
        } else if p.is_file() {
            let rel = p
                .strip_prefix(base)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            out.push(rel);
        }
    }
}

/// E6 / §4.3: the surface-3 color-asset policy checker. PR-blocking.
///
/// * Every file under `assets/color/` has a manifest entry.
/// * Every color entry's provenance is cleared (lightbox-authored / profgen: /
///   community-cleared) and NOTHING is Adobe-authored (provenance, license, or
///   `copyright` field).
/// * The two default looks are present and licensed to the project.
#[test]
fn manifest_policy_checker_clears_every_color_asset() {
    let assets = assets_dir();
    let manifest_path = assets.join("MANIFEST.toml");
    let text = std::fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("missing {} ({e})", manifest_path.display()));
    let manifest: Manifest = toml::from_str(&text).expect("MANIFEST.toml parses");

    // Index color-asset entries by their declared path.
    let color: Vec<&AssetEntry> = manifest
        .asset
        .iter()
        .filter(|a| a.path.starts_with("color/"))
        .collect();

    let is_adobe = |s: &str| s.to_lowercase().contains("adobe");
    let provenance_cleared = |p: &str| {
        p == "lightbox-authored" || p.starts_with("profgen:") || p.starts_with("community:")
    };

    for a in &color {
        assert!(
            provenance_cleared(&a.provenance),
            "{}: provenance {:?} is not in the cleared set",
            a.path,
            a.provenance
        );
        assert!(!is_adobe(&a.provenance), "{}: Adobe provenance", a.path);
        assert!(!is_adobe(&a.license), "{}: Adobe license", a.path);
        if let Some(c) = &a.copyright {
            assert!(!is_adobe(c), "{}: Adobe copyright", a.path);
        }
    }

    // Every file physically present under assets/color/ must be declared.
    let color_dir = assets.join("color");
    let mut files = Vec::new();
    list_files_rel(&assets, &color_dir, &mut files);
    for f in &files {
        assert!(
            color.iter().any(|a| &a.path == f),
            "{f} under assets/color/ has no MANIFEST.toml entry (surface-3 policy)"
        );
    }

    // The two default looks are declared, project-licensed, non-Adobe.
    for want in [
        "color/looks/lightbox-color-v1.lblook",
        "color/looks/lightbox-neutral.lblook",
    ] {
        let e = color
            .iter()
            .find(|a| a.path == want)
            .unwrap_or_else(|| panic!("missing manifest entry for {want}"));
        assert_eq!(e.kind, "look");
        assert_eq!(e.license, "project");
        assert_eq!(e.provenance, "lightbox-authored");
    }
}
