// SPDX-FileCopyrightText: 2026 PixeLabs
// SPDX-License-Identifier: AGPL-3.0-or-later
// Additional terms under AGPL section 7 apply: see COPYING.additional-terms.

//! `cargo xtask bundle-mac`, turn the release binary into a real
//! `Lightbox.app` you can keep in `/Applications`.
//!
//! What it produces:
//!
//! ```text
//! target/macos/Lightbox.app/
//!   Contents/
//!     Info.plist                 identity, version, icon, category, copyright
//!     PkgInfo                    "APPL????"
//!     MacOS/Lightbox             the release binary
//!     MacOS/lightbox-rawproxy    the raw decoder, with --with-libraw
//!     Frameworks/libraw*.dylib   LibRaw and its closure, with --with-libraw
//!     Resources/AppIcon.icns     generated by `icon.rs` → iconutil
//!     Resources/licenses/        LGPL text, with --with-libraw
//! ```
//!
//! **Why the decoder has to be in here.** The shell resolves the decode
//! subprocess by looking for a sibling of its own executable
//! (`ProxyConfig::autodetect`). In a dev tree both binaries sit in
//! `target/release`, so it works. Copying only the shell into the bundle
//! produced an app that silently fell back to the JPEG preview the camera
//! embeds in every raw file: it opened the picture, so it looked fine, and
//! none of the sensor data was there. Shipping the sibling is the whole fix.
//!
//! **Why LibRaw is a separate file rather than linked in.** It is LGPL-2.1,
//! and the licence is satisfied by letting the user substitute their own
//! copy, which a `.dylib` in `Frameworks/` allows and a static link would
//! not. The same separation keeps LibRaw out of the shell binary entirely,
//! which is what lets PixeLabs sell a commercial licence for the app. So the
//! shell is built WITHOUT the feature and only the proxy is built with it.
//!
//! **Signing.** The bundle is signed **ad-hoc** (`codesign --sign -`) when
//! `codesign` is available. That is not Developer ID and does not
//! notarize: it makes macOS treat the bundle as a stable, launchable app
//! locally. A locally built app has no quarantine attribute, so it opens
//! without the "unidentified developer" prompt; anything *downloaded* from
//! the web would need real Developer ID signing + notarization, which is
//! release-engineering work this task deliberately does not pretend to do.
//!
//! **Document types are deliberately absent.** Declaring `CFBundleDocumentTypes`
//! would put Lightbox in "Open With" for every raw file, and then a
//! double-clicked file would arrive as an `application:openFiles:` Apple
//! event, which the shell does not yet handle (E08 Phase H recorded it as
//! toolkit-blocked, owner E16). Advertising an entry point that silently
//! drops the file is worse than not advertising it. Drag-and-drop onto the
//! window, the Open dialogs, and `lightbox <path>` all work today.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};

use crate::icon;

/// Everything the plist and the paths need. Kept in one struct so the
/// "what is this app called" answer lives in exactly one place.
struct BundleSpec {
    /// Bundle + executable name (`Lightbox.app`, `MacOS/Lightbox`).
    name: &'static str,
    /// Reverse-DNS bundle id.
    identifier: &'static str,
    /// `NSHumanReadableCopyright`. Mirrors `lightbox_shell::about::COPYRIGHT`.
    copyright: &'static str,
    /// The cargo bin target to bundle.
    bin: &'static str,
    /// Oldest macOS the bundle claims to run on.
    min_system: &'static str,
    /// Finder/App Store category.
    category: &'static str,
}

const SPEC: BundleSpec = BundleSpec {
    name: "Lightbox",
    identifier: "net.pixelabs.lightbox",
    copyright: "© 2026 PixeLabs",
    bin: "lightbox",
    min_system: "11.0",
    category: "public.app-category.photography",
};

/// `bundle-mac` options.
#[derive(Default)]
pub struct Opts {
    /// Also copy the finished bundle into `/Applications`.
    pub install: bool,
    /// Skip `cargo build --release` (bundle whatever is already built).
    pub no_build: bool,
    /// Build `lightbox-rawproxy --features libraw`, put it beside the shell,
    /// and vendor LibRaw and everything it needs into `Contents/Frameworks`.
    ///
    /// Off by default so a contributor without LibRaw installed can still
    /// produce a bundle. **Every release build must pass it**, because
    /// without it the app cannot read sensor data at all.
    pub with_libraw: bool,
    /// Also wrap the finished bundle in a distributable disk image.
    pub dmg: bool,
}

/// Builds the bundle; returns where it landed.
pub fn run(root: &Path, opts: &Opts) -> Result<PathBuf> {
    if !cfg!(target_os = "macos") {
        bail!("bundle-mac builds a macOS .app bundle and must run on macOS");
    }

    let version = workspace_version(root)?;
    let out_dir = root.join("target/macos");
    let app = out_dir.join(format!("{}.app", SPEC.name));
    let contents = app.join("Contents");
    let macos_dir = contents.join("MacOS");
    let resources = contents.join("Resources");

    if !opts.no_build {
        println!("building {} (release)…", SPEC.bin);
        let status = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
            .current_dir(root)
            .args(["build", "--release", "--bin", SPEC.bin])
            .status()
            .context("run cargo build")?;
        if !status.success() {
            bail!("cargo build --release --bin {} failed", SPEC.bin);
        }
    }
    let binary = root.join("target/release").join(SPEC.bin);
    if !binary.is_file() {
        bail!(
            "{} not found. Run without --no-build, or build it first",
            binary.display()
        );
    }

    // Rebuild the bundle from scratch: a stale Resources file surviving a
    // rename is exactly the sort of thing that makes "it works on my
    // machine" bundles.
    if app.exists() {
        std::fs::remove_dir_all(&app).with_context(|| format!("clear {}", app.display()))?;
    }
    std::fs::create_dir_all(&macos_dir)?;
    std::fs::create_dir_all(&resources)?;

    std::fs::copy(&binary, macos_dir.join(SPEC.name)).with_context(|| {
        format!(
            "copy {} → {}",
            binary.display(),
            macos_dir.join(SPEC.name).display()
        )
    })?;

    bundle_cli(root, &macos_dir, opts.no_build)?;

    if opts.with_libraw {
        bundle_rawproxy(root, &contents, opts.no_build)?;
    } else {
        println!(
            "note: built WITHOUT the raw decoder. This bundle falls back to the \n                   JPEG preview inside a raw file. Pass --with-libraw for a real one."
        );
    }

    bundle_presets(root, &resources)?;

    write_icns(&out_dir, &resources.join("AppIcon.icns"))?;
    std::fs::write(contents.join("Info.plist"), info_plist(&version))?;
    std::fs::write(contents.join("PkgInfo"), "APPL????")?;

    // Before signing, because install_name_tool invalidates a signature and
    // because a bundle that reaches for a library outside itself is the
    // classic "worked on the build machine" failure.
    verify_self_contained(&contents)?;

    codesign_ad_hoc(&app)?;

    println!("bundled {}", app.display());

    if opts.dmg {
        let dmg = build_dmg(&out_dir, &app, &version)?;
        println!("disk image {}", dmg.display());
    }

    if opts.install {
        let dest = PathBuf::from("/Applications").join(format!("{}.app", SPEC.name));
        if dest.exists() {
            std::fs::remove_dir_all(&dest)
                .with_context(|| format!("replace {}", dest.display()))?;
        }
        copy_dir(&app, &dest)?;
        println!("installed {}", dest.display());
    } else {
        println!(
            "drag it to /Applications, or re-run with --install (writes /Applications/{}.app)",
            SPEC.name
        );
    }
    Ok(app)
}

/// System locations whose libraries every Mac already has, so they are
/// referenced rather than copied. Everything else has to come with us.
const SYSTEM_PREFIXES: [&str; 3] = ["/usr/lib/", "/System/", "@rpath/"];

/// Builds `lightbox-rawproxy --features libraw`, places it beside the shell,
/// and vendors the LibRaw dylib closure into `Contents/Frameworks`.
/// Copies the starter preset library into the bundle.
///
/// Without this the app finds no presets at all once it leaves the machine
/// that built it: `bundled_preset_files` used to know only the compile-time
/// source path, so every downloaded copy started with an empty library while
/// the website advertised thirty-six presets. The app did not fail, which is
/// what made it easy to miss; it just quietly had nothing to offer.
fn bundle_presets(root: &Path, resources: &Path) -> Result<()> {
    let src = root.join("assets/presets");
    if !src.is_dir() {
        bail!(
            "{} not found; the bundle would ship no presets",
            src.display()
        );
    }
    let dst = resources.join("presets");
    copy_dir(&src, &dst)?;
    let count = count_xmp(&dst);
    if count == 0 {
        bail!("copied {} but found no .xmp presets in it", src.display());
    }
    println!("  bundled {count} presets");
    Ok(())
}

fn count_xmp(dir: &Path) -> usize {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return 0;
    };
    entries
        .filter_map(|e| e.ok())
        .map(|e| {
            let p = e.path();
            if p.is_dir() {
                count_xmp(&p)
            } else {
                usize::from(p.extension().is_some_and(|x| x == "xmp"))
            }
        })
        .sum()
}

/// Puts `lightbox-cli` inside the bundle, beside the shell.
///
/// Two reasons, and the second is the one that matters. It is half the
/// product: the same engine with no window on it, and the website points
/// people at it. And because `ProxyConfig::autodetect` looks for the decode
/// proxy as a sibling of the running executable, a CLI sitting in `MacOS/`
/// finds `MacOS/lightbox-rawproxy` with no environment variable and no
/// configuration, which is exactly the arrangement that makes full sensor
/// decoding work for someone who only ever downloaded a disk image.
///
/// Users reach it at
/// `/Applications/Lightbox.app/Contents/MacOS/lightbox-cli`.
fn bundle_cli(root: &Path, macos_dir: &Path, no_build: bool) -> Result<()> {
    if !no_build {
        println!("building lightbox-cli (release)…");
        let status = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
            .current_dir(root)
            .args(["build", "--release", "-p", "lightbox-cli"])
            .status()
            .context("run cargo build for lightbox-cli")?;
        if !status.success() {
            bail!("cargo build --release -p lightbox-cli failed");
        }
    }
    let src = root.join("target/release/lightbox-cli");
    if !src.is_file() {
        bail!("{} not found; build it or drop --no-build", src.display());
    }
    std::fs::copy(&src, macos_dir.join("lightbox-cli"))
        .context("copy lightbox-cli into the bundle")?;
    println!("  bundled lightbox-cli");
    Ok(())
}

fn bundle_rawproxy(root: &Path, contents: &Path, no_build: bool) -> Result<()> {
    let macos_dir = contents.join("MacOS");
    let frameworks = contents.join("Frameworks");
    std::fs::create_dir_all(&frameworks)?;

    if !no_build {
        println!("building lightbox-rawproxy (release, --features libraw)…");
        // The rpath is what lets the copied binary find Frameworks/ at run
        // time relative to itself, rather than at the absolute path it was
        // linked against.
        let status = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
            .current_dir(root)
            .env(
                "RUSTFLAGS",
                "-C link-arg=-Wl,-rpath,@executable_path/../Frameworks",
            )
            .args([
                "build",
                "--release",
                "-p",
                "lightbox-rawproxy",
                "--features",
                "libraw",
            ])
            .status()
            .context("run cargo build for lightbox-rawproxy")?;
        if !status.success() {
            bail!(
                "building lightbox-rawproxy with --features libraw failed. \
                 LibRaw must be installed to link against (`brew install libraw`)."
            );
        }
    }

    let proxy_src = root.join("target/release/lightbox-rawproxy");
    if !proxy_src.is_file() {
        bail!(
            "{} not found; build it or drop --no-build",
            proxy_src.display()
        );
    }
    let proxy = macos_dir.join("lightbox-rawproxy");
    std::fs::copy(&proxy_src, &proxy).context("copy lightbox-rawproxy into the bundle")?;

    vendor_dylibs(&proxy, &frameworks)?;

    // LGPL-2.1 obliges us to ship the licence text with the binary.
    let licenses = contents.join("Resources/licenses");
    std::fs::create_dir_all(&licenses)?;
    let lgpl = root.join("LICENSES/LGPL-2.1-or-later.txt");
    if lgpl.is_file() {
        std::fs::copy(&lgpl, licenses.join("LGPL-2.1-or-later.txt"))?;
    } else {
        bail!(
            "{} is missing, and a bundle containing LibRaw may not ship without it",
            lgpl.display()
        );
    }
    Ok(())
}

/// Copies every non-system library `binary` needs into `frameworks`, walking
/// the graph transitively, and rewrites the install names so each one is
/// found through `@rpath` inside the bundle.
fn vendor_dylibs(binary: &Path, frameworks: &Path) -> Result<()> {
    let mut queue = vec![binary.to_path_buf()];
    let mut copied: Vec<String> = Vec::new();

    while let Some(current) = queue.pop() {
        for dep in dylib_deps(&current)? {
            if SYSTEM_PREFIXES.iter().any(|p| dep.starts_with(p)) {
                continue;
            }
            let file = Path::new(&dep)
                .file_name()
                .and_then(|f| f.to_str())
                .unwrap_or_default()
                .to_owned();
            if file.is_empty() {
                continue;
            }
            let dest = frameworks.join(&file);

            if !copied.contains(&file) {
                let src = Path::new(&dep);
                if !src.is_file() {
                    bail!(
                        "{} needs {}, which is not on this machine",
                        current.display(),
                        dep
                    );
                }
                std::fs::copy(src, &dest)
                    .with_context(|| format!("vendor {} into the bundle", dep))?;
                // Copies out of Homebrew are read-only; install_name_tool needs to write.
                let mut perms = std::fs::metadata(&dest)?.permissions();
                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    perms.set_mode(0o755);
                }
                std::fs::set_permissions(&dest, perms)?;
                run_tool(
                    "install_name_tool",
                    &["-id", &format!("@rpath/{file}")],
                    &dest,
                )?;
                copied.push(file.clone());
                queue.push(dest.clone());
                println!("  vendored {file}");
            }

            // Point whoever referenced it at the copy we now own.
            run_tool(
                "install_name_tool",
                &["-change", &dep, &format!("@rpath/{file}")],
                &current,
            )?;
        }
    }
    Ok(())
}

/// `otool -L`, parsed. First line is the file itself, the rest are its
/// dependencies.
fn dylib_deps(path: &Path) -> Result<Vec<String>> {
    let out = Command::new("otool")
        .arg("-L")
        .arg(path)
        .output()
        .context("run otool -L (macOS built-in)")?;
    if !out.status.success() {
        bail!("otool -L failed on {}", path.display());
    }
    Ok(String::from_utf8_lossy(&out.stdout)
        .lines()
        .skip(1)
        .filter_map(|l| l.split_whitespace().next())
        .filter(|l| l.ends_with(".dylib"))
        .map(|s| s.to_owned())
        .collect())
}

fn run_tool(tool: &str, args: &[&str], target: &Path) -> Result<()> {
    let status = Command::new(tool)
        .args(args)
        .arg(target)
        .status()
        .with_context(|| format!("run {tool}"))?;
    if !status.success() {
        bail!("{tool} {:?} failed on {}", args, target.display());
    }
    Ok(())
}

/// Fails if anything in the bundle still reaches for a library outside it.
///
/// This is the check that separates a bundle which works everywhere from one
/// that works only where it was built. Homebrew paths are the usual culprit,
/// because that is where the build machine found LibRaw.
fn verify_self_contained(contents: &Path) -> Result<()> {
    let mut offenders = Vec::new();
    for dir in ["MacOS", "Frameworks"] {
        let dir = contents.join(dir);
        if !dir.is_dir() {
            continue;
        }
        for entry in std::fs::read_dir(&dir)? {
            let path = entry?.path();
            if !path.is_file() {
                continue;
            }
            for dep in dylib_deps(&path).unwrap_or_default() {
                if SYSTEM_PREFIXES.iter().any(|p| dep.starts_with(p)) {
                    continue;
                }
                offenders.push(format!("{} needs {}", path.display(), dep));
            }
        }
    }
    if offenders.is_empty() {
        println!("verified: every binary resolves inside the bundle");
        Ok(())
    } else {
        bail!(
            "the bundle reaches outside itself, so it would only run on this \
             machine:\n  {}",
            offenders.join("\n  ")
        )
    }
}

/// Renders the iconset and folds it into an `.icns` with `iconutil`
/// (ships with macOS; no third-party image tooling involved).
fn write_icns(work: &Path, dest: &Path) -> Result<()> {
    let iconset = work.join("AppIcon.iconset");
    if iconset.exists() {
        std::fs::remove_dir_all(&iconset)?;
    }
    std::fs::create_dir_all(&iconset)?;
    for (name, size) in icon::ICONSET {
        icon::write_png(&iconset.join(name), *size)?;
    }
    let status = Command::new("iconutil")
        .args(["--convert", "icns", "--output"])
        .arg(dest)
        .arg(&iconset)
        .status()
        .context("run iconutil (macOS built-in)")?;
    if !status.success() {
        bail!("iconutil failed to build {}", dest.display());
    }
    std::fs::remove_dir_all(&iconset).ok();
    Ok(())
}

/// Ad-hoc signature, see the module docs for what this does and does not
/// buy.
///
/// **Order is load-bearing and this is where a first attempt always fails.**
/// Signing has to go inside out: every vendored dylib, then the decode proxy,
/// then the shell, and the bundle itself last. Signing only the outer bundle
/// leaves the nested binaries carrying the signature Homebrew shipped, which
/// `install_name_tool` invalidated when it rewrote their install names, and
/// macOS answers an invalid signature by killing the process with SIGKILL the
/// instant it launches. The symptom is a decode proxy that dies on every
/// single file with signal 9 and an app that silently falls back to the
/// embedded preview, which is precisely the bug this whole change exists to
/// remove.
///
/// A missing `codesign` is a warning, not a failure: the bundle still runs.
fn codesign_ad_hoc(app: &Path) -> Result<()> {
    let contents = app.join("Contents");
    let mut targets: Vec<PathBuf> = Vec::new();

    // Innermost first.
    for dir in ["Frameworks", "MacOS"] {
        let dir = contents.join(dir);
        if !dir.is_dir() {
            continue;
        }
        let mut entries: Vec<PathBuf> = std::fs::read_dir(&dir)?
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.is_file())
            .collect();
        entries.sort();
        targets.extend(entries);
    }
    // The bundle itself last.
    targets.push(app.to_path_buf());

    for target in &targets {
        match Command::new("codesign")
            .args(["--force", "--sign", "-", "--timestamp=none"])
            .arg(target)
            .status()
        {
            Ok(status) if status.success() => {}
            Ok(status) => {
                println!(
                    "warning: codesign exited {status} on {}; it will not launch",
                    target.display()
                );
                return Ok(());
            }
            Err(err) => {
                println!("warning: codesign unavailable ({err}); the bundle is unsigned");
                return Ok(());
            }
        }
    }
    println!(
        "signed ad-hoc, inside out, {} item(s) (not Developer ID: a downloaded copy \
         still needs its quarantine flag cleared)",
        targets.len()
    );
    Ok(())
}

/// The `Info.plist`, hand-written rather than templated from a crate: it
/// is nine keys, and a dependency that generates them would be more code
/// to audit than the keys themselves.
fn info_plist(version: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>              <string>{name}</string>
    <key>CFBundleDisplayName</key>       <string>{name}</string>
    <key>CFBundleExecutable</key>        <string>{name}</string>
    <key>CFBundleIdentifier</key>        <string>{id}</string>
    <key>CFBundleIconFile</key>          <string>AppIcon</string>
    <key>CFBundlePackageType</key>       <string>APPL</string>
    <key>CFBundleShortVersionString</key><string>{version}</string>
    <key>CFBundleVersion</key>           <string>{version}</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>LSMinimumSystemVersion</key>    <string>{min_system}</string>
    <key>LSApplicationCategoryType</key> <string>{category}</string>
    <key>NSHighResolutionCapable</key>   <true/>
    <key>NSHumanReadableCopyright</key>  <string>{copyright}</string>
</dict>
</plist>
"#,
        name = SPEC.name,
        id = SPEC.identifier,
        version = version,
        min_system = SPEC.min_system,
        category = SPEC.category,
        copyright = SPEC.copyright,
    )
}

/// `workspace.package.version` from the root manifest, one source of
/// truth with the binary's own `CARGO_PKG_VERSION`.
fn workspace_version(root: &Path) -> Result<String> {
    let text = std::fs::read_to_string(root.join("Cargo.toml")).context("read Cargo.toml")?;
    let manifest: toml::Table = text.parse().context("parse Cargo.toml")?;
    manifest
        .get("workspace")
        .and_then(|w| w.get("package"))
        .and_then(|p| p.get("version"))
        .and_then(|v| v.as_str())
        .map(str::to_owned)
        .context("Cargo.toml has no [workspace.package] version")
}

/// Recursive copy (no `cp -R` shell-out, no dependency).
fn copy_dir(from: &Path, to: &Path) -> Result<()> {
    std::fs::create_dir_all(to)?;
    for entry in std::fs::read_dir(from)? {
        let entry = entry?;
        let (src, dst) = (entry.path(), to.join(entry.file_name()));
        if entry.file_type()?.is_dir() {
            copy_dir(&src, &dst)?;
        } else {
            std::fs::copy(&src, &dst)
                .with_context(|| format!("copy {} → {}", src.display(), dst.display()))?;
        }
    }
    Ok(())
}

/// Wraps the bundle in a disk image, the format a Mac user expects to
/// download: mount it, drag the icon onto the Applications alias, eject.
///
/// The window also carries a plain-text file explaining the "Lightbox is
/// damaged" error, because that error is what an unsigned download produces
/// on macOS 15 and later, and the moment a person needs the explanation is
/// the moment they are looking at this window. See the module docs.
fn build_dmg(out_dir: &Path, app: &Path, version: &str) -> Result<PathBuf> {
    let staging = out_dir.join("dmg-staging");
    if staging.exists() {
        std::fs::remove_dir_all(&staging)?;
    }
    std::fs::create_dir_all(&staging)?;

    copy_dir(app, &staging.join(format!("{}.app", SPEC.name)))?;

    // A symlink, not a copy: this is the standard drag-to-install target.
    std::os::unix::fs::symlink("/Applications", staging.join("Applications"))
        .context("create the Applications alias inside the disk image")?;

    std::fs::write(
        staging.join("If it says damaged, read me.txt"),
        FIRST_RUN_HELP,
    )?;

    let dmg = out_dir.join(format!("{}-{version}.dmg", SPEC.name));
    if dmg.exists() {
        std::fs::remove_file(&dmg)?;
    }

    let status = Command::new("hdiutil")
        .args(["create", "-quiet", "-fs", "HFS+", "-format", "UDZO"])
        .arg("-volname")
        .arg(format!("{} {version}", SPEC.name))
        .arg("-srcfolder")
        .arg(&staging)
        .arg(&dmg)
        .status()
        .context("run hdiutil")?;
    if !status.success() {
        bail!("hdiutil create failed");
    }
    std::fs::remove_dir_all(&staging).ok();
    Ok(dmg)
}

/// Shipped inside the disk image and reproduced on the download page.
///
/// Every word of this is the consequence of shipping without an Apple
/// Developer ID. macOS flags anything a browser downloaded, refuses to open
/// an unsigned app carrying that flag, and words the refusal as "damaged",
/// which is both alarming and untrue. macOS 15 removed the old Control-click
/// escape hatch, so the command below is now the only way through.
const FIRST_RUN_HELP: &str = "\
Lightbox is not damaged.

macOS marks every file a browser downloads, and it refuses to open an
application carrying that mark unless the application is signed with a
certificate from Apple. Lightbox is not signed yet, so you get an error
that says the app is damaged. It isn't. Nothing is wrong with the file.

To open it: drag Lightbox to Applications as usual, then open Terminal
(press Command-Space, type Terminal, press Return) and paste this line:

    xattr -dr com.apple.quarantine /Applications/Lightbox.app

Press Return. Lightbox opens normally from then on, and you never need to
do this again until you install a new version.

If you would rather check the download first, the release page publishes a
SHA-256 fingerprint for every file. Run this and compare it to the one
published beside the download:

    shasum -a 256 ~/Downloads/Lightbox-*.dmg
";

#[cfg(test)]
mod tests {
    use super::*;

    /// The plist must be well-formed enough for `plutil` to parse, and
    /// must carry the identity keys Finder actually reads. A typo here
    /// produces an app that launches but shows up as "lightbox" with a
    /// blank icon.
    #[test]
    fn info_plist_has_the_identity_keys() {
        let plist = info_plist("1.2.3");
        for key in [
            "CFBundleIdentifier",
            "CFBundleExecutable",
            "CFBundleIconFile",
            "CFBundleShortVersionString",
            "NSHighResolutionCapable",
            "NSHumanReadableCopyright",
        ] {
            assert!(plist.contains(key), "plist is missing {key}");
        }
        assert!(plist.contains("<string>1.2.3</string>"));
        assert!(plist.contains(SPEC.identifier));
    }

    /// The copyright shown in Finder's Get Info must be the same string
    /// the About window shows. They live in different crates, so this is
    /// the only place the two can be compared.
    #[test]
    fn plist_copyright_matches_the_about_window() {
        assert_eq!(
            SPEC.copyright, "© 2026 PixeLabs",
            "keep in step with lightbox_shell::about::COPYRIGHT"
        );
        assert!(info_plist("0.1.0").contains(SPEC.copyright));
    }
}
