// SPDX-FileCopyrightText: 2026 PixeLabs
// SPDX-License-Identifier: AGPL-3.0-or-later
// Additional terms under AGPL section 7 apply: see COPYING.additional-terms.

//! `cargo xtask bundle-mac`, turn the release binary into a real
//! `Lightbox.app` you can keep in `/Applications`.
//!
//! What it produces:
//!
//! ```text
//! target/macos/Lightbox.app/
//!   Contents/
//!     Info.plist            identity, version, icon, category, copyright
//!     PkgInfo               "APPL????"
//!     MacOS/Lightbox        the release binary
//!     Resources/AppIcon.icns  generated by `icon.rs` → iconutil
//! ```
//!
//! **Signing.** The bundle is signed **ad-hoc** (`codesign --sign -`) when
//! `codesign` is available. That is not Developer ID and does not
//! notarize: it makes macOS treat the bundle as a stable, launchable app
//! locally. A locally built app has no quarantine attribute, so it opens
//! without the "unidentified developer" prompt; anything *downloaded* from
//! the web would need real Developer ID signing + notarization, which is
//! release-engineering work this task deliberately does not pretend to do.
//!
//! **Document types are deliberately absent.** Declaring `CFBundleDocumentTypes`
//! would put Lightbox in "Open With" for every raw file, and then a
//! double-clicked file would arrive as an `application:openFiles:` Apple
//! event, which the shell does not yet handle (E08 Phase H recorded it as
//! toolkit-blocked, owner E16). Advertising an entry point that silently
//! drops the file is worse than not advertising it. Drag-and-drop onto the
//! window, the Open dialogs, and `lightbox <path>` all work today.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};

use crate::icon;

/// Everything the plist and the paths need. Kept in one struct so the
/// "what is this app called" answer lives in exactly one place.
struct BundleSpec {
    /// Bundle + executable name (`Lightbox.app`, `MacOS/Lightbox`).
    name: &'static str,
    /// Reverse-DNS bundle id.
    identifier: &'static str,
    /// `NSHumanReadableCopyright`. Mirrors `lightbox_shell::about::COPYRIGHT`.
    copyright: &'static str,
    /// The cargo bin target to bundle.
    bin: &'static str,
    /// Oldest macOS the bundle claims to run on.
    min_system: &'static str,
    /// Finder/App Store category.
    category: &'static str,
}

const SPEC: BundleSpec = BundleSpec {
    name: "Lightbox",
    identifier: "net.pixelabs.lightbox",
    copyright: "© 2026 PixeLabs",
    bin: "lightbox",
    min_system: "11.0",
    category: "public.app-category.photography",
};

/// `bundle-mac` options.
#[derive(Default)]
pub struct Opts {
    /// Also copy the finished bundle into `/Applications`.
    pub install: bool,
    /// Skip `cargo build --release` (bundle whatever is already built).
    pub no_build: bool,
}

/// Builds the bundle; returns where it landed.
pub fn run(root: &Path, opts: &Opts) -> Result<PathBuf> {
    if !cfg!(target_os = "macos") {
        bail!("bundle-mac builds a macOS .app bundle and must run on macOS");
    }

    let version = workspace_version(root)?;
    let out_dir = root.join("target/macos");
    let app = out_dir.join(format!("{}.app", SPEC.name));
    let contents = app.join("Contents");
    let macos_dir = contents.join("MacOS");
    let resources = contents.join("Resources");

    if !opts.no_build {
        println!("building {} (release)…", SPEC.bin);
        let status = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
            .current_dir(root)
            .args(["build", "--release", "--bin", SPEC.bin])
            .status()
            .context("run cargo build")?;
        if !status.success() {
            bail!("cargo build --release --bin {} failed", SPEC.bin);
        }
    }
    let binary = root.join("target/release").join(SPEC.bin);
    if !binary.is_file() {
        bail!(
            "{} not found — run without --no-build, or build it first",
            binary.display()
        );
    }

    // Rebuild the bundle from scratch: a stale Resources file surviving a
    // rename is exactly the sort of thing that makes "it works on my
    // machine" bundles.
    if app.exists() {
        std::fs::remove_dir_all(&app).with_context(|| format!("clear {}", app.display()))?;
    }
    std::fs::create_dir_all(&macos_dir)?;
    std::fs::create_dir_all(&resources)?;

    std::fs::copy(&binary, macos_dir.join(SPEC.name)).with_context(|| {
        format!(
            "copy {} → {}",
            binary.display(),
            macos_dir.join(SPEC.name).display()
        )
    })?;

    write_icns(&out_dir, &resources.join("AppIcon.icns"))?;
    std::fs::write(contents.join("Info.plist"), info_plist(&version))?;
    std::fs::write(contents.join("PkgInfo"), "APPL????")?;

    codesign_ad_hoc(&app)?;

    println!("bundled {}", app.display());

    if opts.install {
        let dest = PathBuf::from("/Applications").join(format!("{}.app", SPEC.name));
        if dest.exists() {
            std::fs::remove_dir_all(&dest)
                .with_context(|| format!("replace {}", dest.display()))?;
        }
        copy_dir(&app, &dest)?;
        println!("installed {}", dest.display());
    } else {
        println!(
            "drag it to /Applications, or re-run with --install (writes /Applications/{}.app)",
            SPEC.name
        );
    }
    Ok(app)
}

/// Renders the iconset and folds it into an `.icns` with `iconutil`
/// (ships with macOS; no third-party image tooling involved).
fn write_icns(work: &Path, dest: &Path) -> Result<()> {
    let iconset = work.join("AppIcon.iconset");
    if iconset.exists() {
        std::fs::remove_dir_all(&iconset)?;
    }
    std::fs::create_dir_all(&iconset)?;
    for (name, size) in icon::ICONSET {
        icon::write_png(&iconset.join(name), *size)?;
    }
    let status = Command::new("iconutil")
        .args(["--convert", "icns", "--output"])
        .arg(dest)
        .arg(&iconset)
        .status()
        .context("run iconutil (macOS built-in)")?;
    if !status.success() {
        bail!("iconutil failed to build {}", dest.display());
    }
    std::fs::remove_dir_all(&iconset).ok();
    Ok(())
}

/// Ad-hoc signature, see the module docs for what this does and does not
/// buy. A missing `codesign` is a warning, not a failure: the bundle still
/// runs.
fn codesign_ad_hoc(app: &Path) -> Result<()> {
    match Command::new("codesign")
        .args(["--force", "--sign", "-", "--timestamp=none"])
        .arg(app)
        .status()
    {
        Ok(status) if status.success() => {
            println!("signed ad-hoc (not Developer ID; fine for local use)");
        }
        Ok(status) => println!("warning: codesign exited {status}; the bundle is unsigned"),
        Err(err) => println!("warning: codesign unavailable ({err}); the bundle is unsigned"),
    }
    Ok(())
}

/// The `Info.plist`, hand-written rather than templated from a crate: it
/// is nine keys, and a dependency that generates them would be more code
/// to audit than the keys themselves.
fn info_plist(version: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>              <string>{name}</string>
    <key>CFBundleDisplayName</key>       <string>{name}</string>
    <key>CFBundleExecutable</key>        <string>{name}</string>
    <key>CFBundleIdentifier</key>        <string>{id}</string>
    <key>CFBundleIconFile</key>          <string>AppIcon</string>
    <key>CFBundlePackageType</key>       <string>APPL</string>
    <key>CFBundleShortVersionString</key><string>{version}</string>
    <key>CFBundleVersion</key>           <string>{version}</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>LSMinimumSystemVersion</key>    <string>{min_system}</string>
    <key>LSApplicationCategoryType</key> <string>{category}</string>
    <key>NSHighResolutionCapable</key>   <true/>
    <key>NSHumanReadableCopyright</key>  <string>{copyright}</string>
</dict>
</plist>
"#,
        name = SPEC.name,
        id = SPEC.identifier,
        version = version,
        min_system = SPEC.min_system,
        category = SPEC.category,
        copyright = SPEC.copyright,
    )
}

/// `workspace.package.version` from the root manifest, one source of
/// truth with the binary's own `CARGO_PKG_VERSION`.
fn workspace_version(root: &Path) -> Result<String> {
    let text = std::fs::read_to_string(root.join("Cargo.toml")).context("read Cargo.toml")?;
    let manifest: toml::Table = text.parse().context("parse Cargo.toml")?;
    manifest
        .get("workspace")
        .and_then(|w| w.get("package"))
        .and_then(|p| p.get("version"))
        .and_then(|v| v.as_str())
        .map(str::to_owned)
        .context("Cargo.toml has no [workspace.package] version")
}

/// Recursive copy (no `cp -R` shell-out, no dependency).
fn copy_dir(from: &Path, to: &Path) -> Result<()> {
    std::fs::create_dir_all(to)?;
    for entry in std::fs::read_dir(from)? {
        let entry = entry?;
        let (src, dst) = (entry.path(), to.join(entry.file_name()));
        if entry.file_type()?.is_dir() {
            copy_dir(&src, &dst)?;
        } else {
            std::fs::copy(&src, &dst)
                .with_context(|| format!("copy {} → {}", src.display(), dst.display()))?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The plist must be well-formed enough for `plutil` to parse, and
    /// must carry the identity keys Finder actually reads. A typo here
    /// produces an app that launches but shows up as "lightbox" with a
    /// blank icon.
    #[test]
    fn info_plist_has_the_identity_keys() {
        let plist = info_plist("1.2.3");
        for key in [
            "CFBundleIdentifier",
            "CFBundleExecutable",
            "CFBundleIconFile",
            "CFBundleShortVersionString",
            "NSHighResolutionCapable",
            "NSHumanReadableCopyright",
        ] {
            assert!(plist.contains(key), "plist is missing {key}");
        }
        assert!(plist.contains("<string>1.2.3</string>"));
        assert!(plist.contains(SPEC.identifier));
    }

    /// The copyright shown in Finder's Get Info must be the same string
    /// the About window shows. They live in different crates, so this is
    /// the only place the two can be compared.
    #[test]
    fn plist_copyright_matches_the_about_window() {
        assert_eq!(
            SPEC.copyright, "© 2026 PixeLabs",
            "keep in step with lightbox_shell::about::COPYRIGHT"
        );
        assert!(info_plist("0.1.0").contains(SPEC.copyright));
    }
}
