// SPDX-FileCopyrightText: 2026 Lightbox contributors
// SPDX-License-Identifier: Apache-2.0

//! Content hashing for fixture pins.
//!
//! Pins are **xxh3-128** rendered as lowercase hex of the canonical (big-endian)
//! byte order — the same canonicalization `lightbox-decode::hash_file` adopts
//! in E01 Phase 5, so fixture pins and `ContentHash` values stay comparable.
//! Upstream `sha256` pins (raw.pixls.us publishes them) are verified too when
//! present.

use std::io::Read;
use std::path::Path;

use anyhow::Context;
use sha2::Digest;

/// Streaming xxh3-128 of a file (1 MiB chunks).
pub fn xxh3_128_file(path: &Path) -> anyhow::Result<u128> {
    let mut file = std::fs::File::open(path)
        .with_context(|| format!("cannot open {} for hashing", path.display()))?;
    let mut hasher = twox_hash::XxHash3_128::new();
    let mut buf = vec![0u8; 1 << 20];
    loop {
        let n = file
            .read(&mut buf)
            .with_context(|| format!("read error hashing {}", path.display()))?;
        if n == 0 {
            break;
        }
        hasher.write(&buf[..n]);
    }
    Ok(hasher.finish_128())
}

/// xxh3-128 of an in-memory buffer (test helper for pinning generated bytes).
#[cfg(test)]
pub fn xxh3_128_bytes(bytes: &[u8]) -> u128 {
    twox_hash::XxHash3_128::oneshot(bytes)
}

/// Canonical hex rendering (32 lowercase chars, big-endian byte order).
pub fn xxh3_hex(value: u128) -> String {
    format!("{value:032x}")
}

/// Streaming sha256 of a file, lowercase hex.
pub fn sha256_file(path: &Path) -> anyhow::Result<String> {
    let mut file = std::fs::File::open(path)
        .with_context(|| format!("cannot open {} for hashing", path.display()))?;
    let mut hasher = sha2::Sha256::new();
    let mut buf = vec![0u8; 1 << 20];
    loop {
        let n = file
            .read(&mut buf)
            .with_context(|| format!("read error hashing {}", path.display()))?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    let digest = hasher.finalize();
    let mut out = String::with_capacity(64);
    for b in digest {
        use std::fmt::Write;
        let _ = write!(out, "{b:02x}");
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn xxh3_streaming_matches_oneshot() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("blob");
        // Larger than one chunk to exercise the streaming loop.
        let data: Vec<u8> = (0..(3 << 20) + 17).map(|i| (i % 251) as u8).collect();
        std::fs::write(&path, &data).unwrap();
        assert_eq!(xxh3_128_file(&path).unwrap(), xxh3_128_bytes(&data));
    }

    #[test]
    fn xxh3_hex_is_32_lowercase_chars_and_stable() {
        let h = xxh3_hex(xxh3_128_bytes(b"lightbox"));
        assert_eq!(h.len(), 32);
        assert!(h
            .chars()
            .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()));
        assert_eq!(h, xxh3_hex(xxh3_128_bytes(b"lightbox")));
        assert_ne!(h, xxh3_hex(xxh3_128_bytes(b"lightbox!")));
    }

    #[test]
    fn sha256_known_vector() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("abc");
        std::fs::write(&path, b"abc").unwrap();
        assert_eq!(
            sha256_file(&path).unwrap(),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
    }
}
