// SPDX-FileCopyrightText: 2026 Lightbox contributors
// SPDX-License-Identifier: Apache-2.0

//! `lightbox-render-testkit` — the shared E05 test infrastructure (spec §2/§6).
//!
//! **Dev/test only — NOT shipped.** This crate is the golden-image harness,
//! the self-contained ΔE2000 / PSNR comparators, the probe nodes, and the
//! slider-latency / soak scenario harness that the whole pixel stream
//! (E05/E10/E11/E12/E15) reuses.
//!
//! # Scaffold status (E05 Phase A)
//!
//! Everything here is a **stub** naming its owning phase-task:
//! - [`compare`] — self-contained f64 Lab / ΔE2000 / PSNR — task **A16**
//!   (**A-core**); validated against published ΔE2000 test vectors.
//! - [`corpus`] — corpus manifest format + [`corpus::GoldenCase`] runner +
//!   per-PV golden matrix — task **A16**/**D3** (**A-core**/**D**).
//! - [`probes`] — `test.gain` / `test.blur_r` / `test.accum` / `test.checker`
//!   probe nodes used by the cache / ROI / parity gates — tasks A4/B5/C1/C8.
//! - [`scenario`] — slider-latency p95 + soak harness — tasks **F1**/C10.
//!
//! The corpus (≥ 6 synthetic sources: gradients / checker / low-key / high-key
//! / high-frequency / wide-gamut / 100 MP-synthetic) is generated by
//! [`corpus`]; goldens are rendered from the **CPU reference path** (§4.4 / R3).

pub mod compare;
pub mod corpus;
pub mod probes;
pub mod scenario;
