// SPDX-FileCopyrightText: 2026 Lightbox contributors
// SPDX-License-Identifier: Apache-2.0

//! T11: own minimal libjxl encode FFI (feature `jxl`) + `jxl-oxide` decode
//! (E03 spec §2/§5.3, Risk R1).
//!
//! **Status: encode is UNVERIFIED; decode is real and spike-tested.** This
//! build machine has no libjxl installed (confirmed absent via `brew list`,
//! `pkg-config --exists libjxl`, and a binary/header search — none found;
//! see `docs/plan/epics/E03-deviations.md`, Phase C T11) — the FFI surface
//! this module's `encode` calls is generated by `build.rs`'s `bindgen` step
//! *at build time* from whatever real `jxl/encode.h` is present, which
//! means it has never actually been generated, compiled, or linked in this
//! repository. The functions/structs named below (`JxlEncoderCreate`,
//! `JxlEncoderInitBasicInfo`, `JxlBasicInfo`, `JxlPixelFormat`, …) are
//! libjxl's own stable, publicly documented C API (unchanged in shape since
//! ~0.8), modeled directly on libjxl's own `examples/encode_oneshot.c`
//! reference sequence — but the field-level correctness of `JxlBasicInfo`
//! (a large struct) is guaranteed ONLY because `bindgen` reads it from the
//! real installed header rather than a hand-transcription; this file itself
//! contains no struct-layout guesses.
//!
//! [`decode_jxl_oxide`] is different: `jxl-oxide` is pure Rust (no libjxl
//! needed), so it *can* be compiled and exercised without a native library.
//! It was spike-verified in a scratch crate against a real downloaded JXL
//! codestream (libjxl's own conformance corpus, `bicycles/input.jxl`) during
//! this phase's development and decoded correctly (1024×631, 3-channel
//! RGB8, exact expected byte count) — high confidence, even though it is
//! still gated behind `jxl` alongside the encode half per the task's "gate
//! the whole module" instruction (a JXL file can only exist on disk if
//! something encoded one, and only this feature's own encoder — or a
//! future rendered-T1 producer, E05 — would ever write one).
//!
//! The live encode→decode round-trip test below is `#[ignore]`d
//! ("DEFERRED (libjxl absent)") rather than fabricated, per the task's
//! honest-reporting mandate.

#![allow(unsafe_code)] // FFI exception (workspace lints doc comment: "only
                       // lightbox-render... and future FFI crates may
                       // locally `#![allow(unsafe_code)]` with
                       // justification") — this module is the FFI crate
                       // boundary named there, scoped to this one
                       // feature-gated file only.

use super::{CodecError, PreviewCodec, RgbImage};
use crate::config::Codec;

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/jxl_bindings.rs"));
}

pub(crate) struct JxlCodec;

impl PreviewCodec for JxlCodec {
    fn codec(&self) -> Codec {
        Codec::Jxl
    }

    fn encode(&self, img: &RgbImage, quality: u8) -> Result<Vec<u8>, CodecError> {
        // SAFETY: every raw pointer passed to libjxl below is either (a) a
        // `&mut` local's address, live for the whole call, or (b) `img.px`'s
        // slice pointer/len, live for the whole `encode_inner` call (`img`
        // outlives it). The encoder handle (`enc`) is checked non-null
        // immediately after creation and destroyed on every exit path
        // (including early `?` returns, via the `Guard` drop below).
        // Sequence modeled on libjxl's own `examples/encode_oneshot.c` —
        // see this module's doc comment for the verification status.
        unsafe { encode_inner(img, quality) }
    }

    fn decode(&self, bytes: &[u8]) -> Result<RgbImage, CodecError> {
        decode_jxl_oxide(bytes)
    }
}

/// cjxl's own `--quality` → butteraugli-distance conversion (piecewise;
/// matches the JPEG-familiar "higher is better, 0..100" convention this
/// crate's `VariantParams::quality`/`mozjpeg` already use, mapped onto
/// libjxl's "lower distance is better" scale). Copied from libjxl's
/// long-stable `cjxl` quality-to-distance formula; UNVERIFIED against a
/// real libjxl build in this repository (module doc comment).
fn quality_to_distance(quality: u8) -> f32 {
    let q = f64::from(quality.min(100));
    let distance = if q >= 100.0 {
        0.0
    } else if q >= 30.0 {
        0.1 + (100.0 - q) * 0.09
    } else {
        (53.0 / 3000.0) * q * q - (23.0 / 20.0) * q + 25.0
    };
    distance as f32
}

/// RAII guard so `JxlEncoderDestroy` runs on every exit path (including an
/// early `?` return partway through the encode sequence).
struct EncoderGuard(*mut bindings::JxlEncoder);

impl Drop for EncoderGuard {
    fn drop(&mut self) {
        if !self.0.is_null() {
            // SAFETY: `self.0` was returned by `JxlEncoderCreate` and not
            // yet destroyed (this is the only place that destroys it).
            unsafe { bindings::JxlEncoderDestroy(self.0) };
        }
    }
}

unsafe fn encode_inner(img: &RgbImage, quality: u8) -> Result<Vec<u8>, CodecError> {
    let expect = (img.width as usize)
        .checked_mul(img.height as usize)
        .and_then(|n| n.checked_mul(3))
        .ok_or_else(|| CodecError::Encode("RGB8 buffer size overflow".to_owned()))?;
    if img.px.len() != expect {
        return Err(CodecError::Encode(format!(
            "RGB8 buffer length {} != {}x{}x3",
            img.px.len(),
            img.width,
            img.height
        )));
    }

    let enc = bindings::JxlEncoderCreate(std::ptr::null());
    if enc.is_null() {
        return Err(CodecError::Encode("JxlEncoderCreate returned NULL".into()));
    }
    let guard = EncoderGuard(enc);

    let frame_settings = bindings::JxlEncoderFrameSettingsCreate(enc, std::ptr::null());
    if frame_settings.is_null() {
        return Err(CodecError::Encode(
            "JxlEncoderFrameSettingsCreate returned NULL".into(),
        ));
    }
    check(
        bindings::JxlEncoderSetFrameDistance(frame_settings, quality_to_distance(quality)),
        "JxlEncoderSetFrameDistance",
    )?;

    let mut basic_info: bindings::JxlBasicInfo = std::mem::zeroed();
    bindings::JxlEncoderInitBasicInfo(&mut basic_info);
    basic_info.xsize = img.width;
    basic_info.ysize = img.height;
    basic_info.bits_per_sample = 8;
    basic_info.exponent_bits_per_sample = 0;
    basic_info.num_color_channels = 3;
    // T1 stores un-rotated pixels, same convention as T0 (spec §3.5's
    // orientation baking happens uniformly at decode-for-display time,
    // `decode.rs`) — tag the container as already-identity-oriented so a
    // future JXL-aware decode path never double-rotates.
    basic_info.orientation = bindings::JxlOrientation_JXL_ORIENT_IDENTITY;
    check(
        bindings::JxlEncoderSetBasicInfo(enc, &basic_info),
        "JxlEncoderSetBasicInfo",
    )?;

    let mut color_encoding: bindings::JxlColorEncoding = std::mem::zeroed();
    bindings::JxlColorEncodingSetToSRGB(&mut color_encoding, bindings::JXL_FALSE as i32);
    check(
        bindings::JxlEncoderSetColorEncoding(enc, &color_encoding),
        "JxlEncoderSetColorEncoding",
    )?;

    let pixel_format = bindings::JxlPixelFormat {
        num_channels: 3,
        data_type: bindings::JxlDataType_JXL_TYPE_UINT8,
        endianness: bindings::JxlEndianness_JXL_NATIVE_ENDIAN,
        align: 0,
    };
    check(
        bindings::JxlEncoderAddImageFrame(
            frame_settings,
            &pixel_format,
            img.px.as_ptr().cast(),
            img.px.len(),
        ),
        "JxlEncoderAddImageFrame",
    )?;
    bindings::JxlEncoderCloseInput(enc);

    let mut out = vec![0u8; (expect / 4).max(4096)];
    let mut filled = 0usize;
    loop {
        let mut avail_out = out.len() - filled;
        let mut next_out = out.as_mut_ptr().add(filled);
        let status = bindings::JxlEncoderProcessOutput(enc, &mut next_out, &mut avail_out);
        filled = out.len() - avail_out;
        match status {
            bindings::JxlEncoderStatus_JXL_ENC_SUCCESS => break,
            bindings::JxlEncoderStatus_JXL_ENC_NEED_MORE_OUTPUT => {
                let grown = out.len() * 2;
                out.resize(grown, 0);
            }
            _ => {
                return Err(CodecError::Encode(format!(
                    "JxlEncoderProcessOutput failed (status={status})"
                )))
            }
        }
    }
    out.truncate(filled);
    drop(guard);
    Ok(out)
}

unsafe fn check(status: bindings::JxlEncoderStatus, what: &str) -> Result<(), CodecError> {
    if status == bindings::JxlEncoderStatus_JXL_ENC_SUCCESS {
        Ok(())
    } else {
        Err(CodecError::Encode(format!(
            "{what} failed (status={status})"
        )))
    }
}

/// `jxl-oxide` decode to interleaved RGB8 — pure Rust, no libjxl needed.
/// Spike-verified against a real JXL codestream (this module's doc
/// comment); orientation is applied by `jxl-oxide` itself
/// (`Render::stream_no_alpha`'s own doc comment: "Orientation is applied"),
/// which is consistent with [`encode_inner`] always tagging
/// `JXL_ORIENT_IDENTITY` (a no-op orientation transform) — matches T0/T1's
/// shared "unrotated store, baked at read time" convention rather than
/// double-applying it.
fn decode_jxl_oxide(bytes: &[u8]) -> Result<RgbImage, CodecError> {
    let image = jxl_oxide::JxlImage::builder()
        .read(std::io::Cursor::new(bytes))
        .map_err(|e| CodecError::Decode(e.to_string()))?;
    let render = image
        .render_frame(0)
        .map_err(|e| CodecError::Decode(e.to_string()))?;
    let mut stream = render.stream_no_alpha();
    let (width, height, channels) = (stream.width(), stream.height(), stream.channels());
    if channels != 3 {
        return Err(CodecError::Decode(format!(
            "expected 3 RGB channels from a T1 JXL preview, got {channels}"
        )));
    }
    let mut px = vec![0u8; (width as usize) * (height as usize) * 3];
    let written = stream.write_to_buffer(&mut px);
    if written != px.len() {
        return Err(CodecError::Decode(format!(
            "JXL stream wrote {written} of {} expected samples",
            px.len()
        )));
    }
    Ok(RgbImage { px, width, height })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quality_to_distance_is_monotonic_and_zero_at_100() {
        assert_eq!(quality_to_distance(100), 0.0);
        let mut prev = quality_to_distance(0);
        for q in 1..=100u8 {
            let d = quality_to_distance(q);
            assert!(d <= prev, "distance must not increase as quality rises");
            prev = d;
        }
    }

    /// T11 AC: "encode→jxl-oxide-decode round trip within tolerance."
    /// DEFERRED — libjxl is not installed on this build machine, so the
    /// `jxl` feature (and therefore this whole module) has never been
    /// compiled, let alone linked and run. Fabricating a passing result
    /// here would violate the task's honest-reporting mandate; this test
    /// exists (rather than being omitted) so the AC's intent is visible and
    /// the moment libjxl becomes available in the build environment, this
    /// is the test to un-ignore first (E03-deviations.md, Phase C T11).
    #[test]
    #[ignore = "DEFERRED: libjxl is not installed on this build machine (no headers/lib to bindgen/link against); un-ignore once it is"]
    fn encode_decode_round_trip_within_tolerance() {
        let img = RgbImage {
            px: vec![128u8; 32 * 32 * 3],
            width: 32,
            height: 32,
        };
        let codec = JxlCodec;
        let encoded = codec.encode(&img, 90).unwrap();
        let decoded = codec.decode(&encoded).unwrap();
        assert_eq!((decoded.width, decoded.height), (32, 32));
    }
}
