# SPDX-FileCopyrightText: 2026 PixeLabs
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional terms under AGPL section 7 apply: see COPYING.additional-terms.

[alias]
xtask = "run --package xtask --"
